### ISSUE TITLE
Tickets

### ISSUE THREAD

**Issue by ghost** [Shafeman/BarbarianTheater#1]
Ticket Classes:
Yet to implement a ticket serial number.
Not sure of a way to set the discounted prices.(Inside the class or during the transaction)
(moved price format to a separate issue. It looks like you have the discounted price thing working out.)

**Comment by Shafeman** [comment]
For the serial number, I propose we convert Show name to its ASCII digits and take the first 6 numbers. Add the month, day, year (just the numbers). Follow it up with a unique counter stored in Box Office, and finish with the total seat count for the show. If we want, we can append an r, a, or s to the number to indicate the type of ticket.

That will give us a complicated, unique number that is 14+ characters long and has the pertinent information on it for the ticket taker at the door (if we had one). We could drop the ASCII digits if we want to shorten the number, and add 0s between the BoxOffice ticket count and the seat number to make things clear. The format then would be:
mmddyy[BO #]0[seat]x with x being the ticket type (character or integer). That ends up being 10+ characters. I kind of like this way better.

**Comment by ghost** [comment]
I started to implement your second idea for the serial #. (mmddyy[BO #]0[seat]x), So far I have only worked with the first 6 digits. I'm not sure what the Box office number is, is the seat number the number of tickets that have been sold for a show?

**Comment by ghost** [comment]
Also I figure we could use dynamic binding to append the type of ticket at the end of the serial #, using the generateSerialNumber() in the corresponding child classes.

**Comment by Shafeman** [comment]
I was thinking about this a little more on my way in to work. Other than future bookkeeping, I can't think of any reason that we need a separate counter in BoxOffice. Let's strip that part out and just use the ticket sales count from Show. That can just be a private integer with a getter that increments every time a ticket gets sold.

**Comment by kangn** [comment]
we have a counter in theaterpatronIdServer should we maybe changed the class name and use that as a counter for everything?

**Comment by kangn** [comment]
I was about to do some coding and stuff is broken all over I dont see the theaterpatronlist is this still to be implemented?

**Comment by Shafeman** [comment]
Not sure why the list didn't push. I'll figure it out when I get home. I hate git/Eclipse. It probably added the new class to the local .gitignore or something.

We need a show specific ticket counter to make sure we don't sell more tickets than seats, which is why I thought we'd use that. It just seemed like less coupling (tickets are probably already linked to Shows through Transactions, unless we find a better way to return tickets by a specific date) and less work (already need the counter vs changing a class name and all of its references). It's no big deal either way.

**Comment by Shafeman** [comment]
Matchable and TheaterPatronList are available now. I'll be online later.

**Comment by ghost** [comment]
So no boxoffice number for the SN on a tix? Like, MMDDYY[0]Seat#/SeatCap:Type  Like (09211503/70R)   Maybe not even a slash...

**Comment by Shafeman** [comment]
Seat cap isn't necessary as it's not unique. Every ticket would end up with that number. It's two lines of code whether you decide to implement with the Id Server or the Show seat count. So just pick one and go with it. My view of pros/cons below. Whoever gets to it first should just make a decision and implement it. We can change it later if we need to.

ID Server Pro: No need to pass an extra reference to ticket. Just get instance of id server and done.
ID Server Con: May want to rename TheaterPatronIdServer, which impacts the whole system. May not be necessary, though, since Tickets are sold to a TheaterPatron(the Member).

Show Count Pro: No need to rename Id Server
Show Count Con: Have to pass Show into Ticket constructor. 
Show Count Con: If theater ever refunds tickets, SerialNumber won't be unique, since seat count would get decremented. (Not an issue for this assignment.)

**Comment by Shafeman** [comment]
Serial number is working now. I changed the serial number in Ticket to protected instead of private so that the subclass constructor can call serialNumber = this.generateId(ticketType); Not sure if that is correct, so I'm going to leave this open for either of you to review. Feel free to close if you agree.

**Comment by ghost** [comment]
Looks good
